name: Theodore Bouloukos
favicon: null
layout_spectrum: 0.20496933395043015
typography_spectrum: 0.3325052985455841
title: SAG-AFTRA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9077223083004355
  lightness: 0.7660393309779465
  saturation: 0.04695935710333288
  rhythmicContrast: 0.15459455852396786
purpose: []
